In [21]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
with open('apple-computers.txt', mode = 'r') as f:
    apple_comp = f.read()

In [23]:
with open('apple-fruit.txt', mode = 'r') as f:
    apple_fruit = f.read()

In [24]:
test = ["Apple already plans to buy back `$100 billion in shares, including $`16 billion worth last quarter. Icahn probably pounded the dinner table he and Cook shared recently for their much-reported bread-breaking at Icahn's New York apartment. Apple's cash stash currently sits at a whopping `$145 billion but only $`43 billion is in the U.S., which is why Icahn wants to float bonds to cover a buy back.", 
"Fortunately, there are “low-chill” apple varieties for temperate climates. (Chilling hours are defined as nonconsecutive hours of winter temperatures below 45 degrees.) As a general guide, if you live on or near the coast, your garden gets only 100 to 200 chilling hours. Inland San Diego gardens get about 400 to 500 chilling hours — still considered “low chill.”", 
"If this seems a bit like déjà vu, you’ll recall that Apple just held an event to unveil two new iPhone models – the 5c and 5s – back on September 10."]

In [25]:
corpus = [apple_comp, apple_fruit, test[0], test[1], test[2]]
corpuslim = [apple_comp, apple_fruit]

In [26]:
vectorizer = TfidfVectorizer()

In [27]:
tfidfvecs = vectorizer.fit_transform(corpuslim)

In [28]:
testvecs = vectorizer.transform(test)

In [29]:
pd.DataFrame(testvecs.todense())

0     1     2     3     4     5     6     7     8     9     ...   3989  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   

   3990  3991  3992  3993  3994  3995  3996  3997  3998  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[3 rows x 3999 columns]

In [ ]:
def cos_sim(base_vecs, test_vecs):
        comp_vec, fruit_vec = base_vecs[0], base_vecs[1]
        comp_norm, fruit_norm = np.linalg.norm(comp_vec), np.linalg.norm(fruit_vec)
        
        compdots = comp_vec.dot(test_vecs.T)
        fruitdots = fruit_vec.dot(test_vecs.T)
        
        norms = np.linalg.norm(test_vecs.todense(), axis=1)
        
        comps = compdots / (comp_norm * norms)
        fruits = fruitdots / (fruit_norm * norms)
        
        c = np.zeros((comps.shape[1],2))
        c[:,0] = comps
        c[:,1] = fruits
        
        labels = c.argmax(axis=1)
        
        d = {0: 'computer-company', 1: 'fruit'}
        
        return [d[i] for i in labels]


In [32]:
pd.DataFrame(tfidfvecs.todense())

0         1         2         3         4         5         6     \
0  0.015042  0.000000  0.000000  0.001321  0.000000  0.000000  0.000000   
1  0.009857  0.002771  0.002771  0.000000  0.002771  0.002771  0.002771   

       7         8         9       ...         3989      3990      3991  \
0  0.001321  0.000000  0.001321    ...     0.000000  0.001321  0.001321   
1  0.000000  0.002771  0.000000    ...     0.002771  0.000000  0.000000   

       3992      3993      3994      3995      3996      3997      3998  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.005541  0.002771  0.002771  0.002771  0.002771  0.002771  0.013853  

[2 rows x 3999 columns]

In [37]:
tfidfvecs.todense()[1]

matrix([[0.00985683, 0.00277068, 0.00277068, ..., 0.00277068, 0.00277068,
         0.01385342]])

In [38]:
compv = tfidfvecs.todense()[0]
compnorm = np.linalg.norm(compv)

compv.shape

(1, 3999)

In [39]:
testvecs.shape

(3, 3999)

In [50]:
compdottest = compv.dot(testvecs.todense().T)

In [43]:
testvecs

<3x3999 sparse matrix of type '<class 'numpy.float64'>'
	with 98 stored elements in Compressed Sparse Row format>

In [51]:
testmorms = np.linalg.norm(testvecs.todense(), axis=1)

In [64]:
qq = compdottest / (testmorms * compnorm)

In [65]:
qq.shape

(1, 3)

In [57]:
a = np.array([1,2,3,10,20,30])
b = np.array([4,5,6,1,2,3])

list(zip(a,b))

[(1, 4), (2, 5), (3, 6), (10, 1), (20, 2), (30, 3)]

In [61]:
[max(i) for i in list(zip(a,b))]

[4, 5, 6, 10, 20, 30]

In [62]:
c = np.zeros((6,2))
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [63]:
c[:,0] = a
c[:,1] = b
c

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.],
       [10.,  1.],
       [20.,  2.],
       [30.,  3.]])

In [70]:
labels = c.argmax(axis=1)
d = {0: 'computer-company', 1: 'fruit'}

[d[i] for i in labels]

['fruit',
 'fruit',
 'fruit',
 'computer-company',
 'computer-company',
 'computer-company']

In [75]:
allvecs[:2,:]

<2x4031 sparse matrix of type '<class 'numpy.float64'>'
	with 4617 stored elements in Compressed Sparse Row format>

In [76]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

def cos_sim(base_vecs, test_vecs):
        comp_vec, fruit_vec = base_vecs[0], base_vecs[1]
        comp_norm, fruit_norm = np.linalg.norm(comp_vec), np.linalg.norm(fruit_vec)
        
        compdots = comp_vec.dot(test_vecs.T)
        fruitdots = fruit_vec.dot(test_vecs.T)
        
        norms = np.linalg.norm(test_vecs, axis=1)
        
        comps = compdots / (comp_norm * norms)
        fruits = fruitdots / (fruit_norm * norms)
        
        c = np.zeros((comps.shape[1],2))
        c[:,0] = comps
        c[:,1] = fruits
        
        labels = c.argmax(axis=1)
        
        d = {0: 'computer-company', 1: 'fruit'}
        
        return [d[i] for i in labels]


if __name__ == '__main__':

    with open('apple-computers.txt', mode = 'r') as f:
        apple_comp = f.read()
    with open('apple-fruit.txt', mode = 'r') as f:
        apple_fruit = f.read()


    n = int(input())
    corpus = [apple_comp, apple_fruit]

    for i in range(n):
        corpus.append(input())

    vectorizer = TfidfVectorizer()
    vecs = vectorizer.fit_transform(corpus)

    bv = vecs[:2,].todense()
    tv = vecs[2:,].todense()

    ans = cos_sim(bv, tv)

    for i in ans:
        print(i)

ValueError: invalid literal for int() with base 10: ''